<a href="https://colab.research.google.com/github/khushalvanani/Machine-Learning-repo/blob/main/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [23]:
#Importing all the libraries that we would need downstram
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [24]:
#here read_csv is a function from pandas. It is creating a dataframe with values of Data.csv file
dataset = pd.read_csv("Data.csv")
#Independent Variable-- X and dependent variable y
#X is all the columns except the last one so upto -1 and for y it is the last column so -1.
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [8]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Taking care of missing data

In [25]:
#To take care of missing data we need to import impute module and its SimpleImputer class.
from sklearn.impute import SimpleImputer
#now we need to instantiate an object of SimpleImputer class
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
#here the arguments are which missing values we need to replace for and stragey='mean ' means that we'll replace it with mean value.
#here we only created object we didn't connect with X  
#It only expects numerical values 
imputer.fit(X[:,1:3])
#it will fit means calculate the necessary values like mean and stuff
#to apply the transformation we need to apply another function this time it will return new updated version so we need to give it to the X
X[:,1:3] = imputer.transform(X[:,1:3])

In [26]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [27]:
#to encode we need to use two classes coulmntransformer and onehotencoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#In ct object there are two arguments transformer and encoder
#in transformer input will be a list and inside 3-tuple 
#1st element will be enocder 2nd will be what encoder we'll use and the third is index value
#2nd argument is what we're going  to do with remainder columns
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
#this needs to be a numpy array because future m.l model will need it to be a numpy array



In [28]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [29]:
#here dependent variable is only yes and no so we can convert it to 0 and 1 using LabelEncoder class from preprocessing module
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#this doesn't need to be a numpy array
y = le.fit_transform(y)

In [30]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [31]:
#we split the dataset into X_train and X_test because after our model i=has been trianed we need to check if it generalizing well or not.
#In other words if it's doing well on yet unseen data
from sklearn.model_selection import train_test_split
#arguments to pass in are both X and y and test_size,random state=1 because we want the same random partion as instructor
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=1)

In [32]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [33]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [34]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [35]:
print(y_test)

[0 1]


## Feature Scaling

In [36]:
#For feature scaling we need o use StandardScaler because data is in normal distribution
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train[:,3:] = sc.fit_transform(X_train[:,3:])
#here we want the same scaler as the X_train so we only do the transform here for X-test because we want our data to be new
#If we apply fit_transform then we would get a new scalar that is not good because our model will use that to learn not test
X_test[:,3:] = sc.transform(X_test[:,3:])

In [37]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [38]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
